GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/11

###

DELETE http://localhost:3001/api/persons/69e796732f083fed236a2f21

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sam",
    "number": "155-5555"
}

###

PUT http://localhost:3001/api/persons/69e71d2a61d3f4dd354a41e5
Content-Type: application/json

{
    "name": "Anna",
    "number": "123-1111111"
}

###

GET http://localhost:3001/wrongEndpoint