GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/123

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Cooking",
    "author": "Anna",
    "url": "http://bbb"
}