GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/123

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Cooking",
    "author": "Anna",
    "url": "http://bbb"
}

###

PUT http://localhost:3003/api/blogs/23
Content-Type: application/json

{
    "likes": 444
}

###

DELETE http://localhost:3003/api/blogs/69f0dadad5baef29c3e8162e